### ISSUE TITLE
diffrent output of color presets in Home App

### ISSUE THREAD

**Issue by Arijuz** [satrik/homebridge-bslamp2#2] opened 2022-02-28 09:35 UTC
Thanks for your plugin! I works well and so far I am so thankful for they do not loose connection like they did when they were nativly paired, but...

...it looks like there is a problem with the colorsettings. 

I have two Mi Smart Beside Lamp 2...
...when both paired via your plugin the same colorsetting lead to a diffrent output on the lamps (using the 6 presets after default settings).
When pairing nativly the problem does not occur. I then get exact the same output on both lamps.

Have a look on it please. Thank You!

**Comment by satrik** [comment] 2022-02-28 18:34
hi, I also have 2 lamps and I don't have any issues with the colors.
check the homebridge logs to see if the same values for hue/saturation gets send to the lamps. you can also check with the shortcuts app the state of the current set values.

**Comment by Arijuz** [comment] 2022-03-01 06:16
Thanks for answering...
```
[28.2.2022, 10:42:21] [Ns Nachttischlampe] set 'On' to => true
[28.2.2022, 10:42:29] [As Nachttischlampe] set 'On' to => true
[28.2.2022, 10:42:32] [As Nachttischlampe] set 'Brightness' to => 100
[28.2.2022, 10:42:41] [Ns Nachttischlampe] set 'Brightness' to => 100
[28.2.2022, 10:42:46] [Ns Nachttischlampe] set 'Saturation' to => 10
[28.2.2022, 10:42:46] [Ns Nachttischlampe] set 'Hue' to => 331
[28.2.2022, 10:43:05] [As Nachttischlampe] set 'Saturation' to => 10
[28.2.2022, 10:43:05] [As Nachttischlampe] set 'Hue' to => 331
```
...leads to [As Nachtischlampe] white and [Ns Nachtischlampe] white with a pink touch

I will try to reset and pair again to see if there is anything I missed during the setup.

**Comment by satrik** [comment] 2022-03-01 11:50
the [hap-contoller](https://github.com/Apollon77/hap-controller-node) package had 2 updates since I released this plugin. one change was 
```
(Apollon77) Make sure calls on a http connection are queued to not overlap
```
maybe there is something "slower" in your network as in mine and the 2 values won't get published correct to the lamps. I will make some tests with updated hap-controller to see if it works correctly and will then update the bslamp plugin.

**Comment by Arijuz** [comment] 2022-03-01 14:33
Perfect, ty

**Comment by GoanSausage** [comment] 2022-03-10 11:21
Thank you _so_ much. 🙏🏽

After _months_ of struggling with my 4 Mi BS2 Lamps, I decided to do something about it today. After realising that Xiaomi has deliberately borked the LAN functionality of these, I came across your HB plugin.

Install and config could not be easier and so far the connection looks solid. Will report back after a couple of days if Siri and HK automations work reliably.

**Comment by GoanSausage** [comment] 2022-03-10 11:22
> the [hap-contoller](https://github.com/Apollon77/hap-controller-node) package had 2 updates since I released this plugin. one change was
> 
> ```
> (Apollon77) Make sure calls on a http connection are queued to not overlap
> ```
> 
> maybe there is something "slower" in your network as in mine and the 2 values won't get published correct to the lamps. I will make some tests with updated hap-controller to see if it works correctly and will then update the bslamp plugin.

Just wanted to say...

Thank you _so_ much. 🙏🏽

After _months_ of struggling with my 4 Mi BS2 Lamps, I decided to do something about it today. After realising that Xiaomi has deliberately borked the LAN functionality of these, I came across your HB plugin.

Install and config could not be easier and so far the connection looks solid. Will report back after a couple of days if Siri and HK automations work reliably.

**Comment by satrik** [comment] 2022-03-10 12:31
@GoanSausage thank you :) would be nice if you can also test if your colors are set correct or if you also have the issues from @Arijuz

**Comment by GoanSausage** [comment] 2022-03-10 12:50
> @GoanSausage thank you :) would be nice if you can also test if your colors are set correct or if you also have the issues from @Arijuz

Asking Siri to turn all the lamps to any colour results in the same colour across all lamps. The colour presets in Home also work uniformly across lamps.

The only thing I could ask for is an ability to get the high brightness/warm white mode accessible through Home app, something that is currently only possible with the Yeelight/Mi Home app or by holding the upper touch button on the lamp itself.

**Comment by satrik** [comment] 2022-03-10 20:01
What do you mean with "high brightness/warm white mode"? 

If you press `Edit` on a preset in HomeKit, you get 2 "tabs" - one to set color and one to set temperature.

**Comment by GoanSausage** [comment] 2022-03-11 03:31
> What do you mean with "high brightness/warm white mode"?
> 
> If you press `Edit` on a preset in HomeKit, you get 2 "tabs" - one to set color and one to set temperature.

There is a colour mode and then a white lamp mode on the BSII's. The white lamp mode can only be accessed from their own apps and by holding down the top button on the lamps itself.

This mode isn't exposed to HK. It's much brighter than any colour temp/brightness available in HK. 

I'm guessing there are additional white LEDs inside the lamp in addition to the RGB LEDs. These white LEDs only come on in this mode. 

Try it yourself.

**Comment by satrik** [comment] 2022-03-11 08:36
Oh, I didn't know this mode 😄 I will check if this mode can be accessed through the exposed HomeKit api of the lamps.

**Comment by satrik** [comment] 2022-03-11 16:24
@GoanSausage there is no option exposed to toggle this mode, so no way for me to add this mode...

**Comment by GoanSausage** [comment] 2022-03-12 07:57
> @GoanSausage there is no option exposed to toggle this mode, so no way for me to add this mode...

I thought so, since the functionality isn't exposed to HomeKit. 

No worries, connectivity and responsiveness have been rock sold since install. 🙏🏽

**Comment by satrik** [comment] 2022-07-13 09:02
as no one else reported or confirmed this issue, I will close it now

**Closed as completed by satrik** 2022-07-13 09:02 UTC

**Comment by satrik** [comment] 2022-10-29 08:25
@Arijuz I have more or less rewritten the complete plugin to work with the new functions of the hap-controller package.
would be interesting to know if your color issue still exists now 🙂

**Comment by Arijuz** [comment] 2022-10-30 08:36
> 

Hi, I’ll have a look at it these days. Will reply later next week. Greetings
